'''BigFrame'''
def main():
    '''BigFrame'''
    y1 = str(input().rstrip())
    y2 = str(input().rstrip())
    y3 = str(input().rstrip())
    y4 = str(input().rstrip())
    y5 = str(input().rstrip())
    l1 = [len(y1),len(y2),len(y3),len(y4),len(y5)]
    a = max(l1)
    print("*"*(a+4))
    print("*",end = " ")
    print(y1,end =" ")
    print(" "*(a-len(y1)),end ="")
    print("*")
    print("*",end = " ")
    print(y2,end =" ")
    print(" "*(a-len(y2)),end ="")
    print("*")
    print("*",end = " ")
    print(y3,end =" ")
    print(" "*(a-len(y3)),end ="")
    print("*")
    print("*",end = " ")
    print(y4,end =" ")
    print(" "*(a-len(y4)),end ="")
    print("*")
    print("*",end = " ")
    print(y5,end =" ")
    print(" "*(a-len(y5)),end ="")
    print("*")
    print("*"*(a+4))
main()
